name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          xcodebuild -scheme TurboNavigator test -quiet -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro"
